#web:
#  image: pdxjohnny/textbooks-server
#  ports:
#    - "8080:8080"
#  links:
#    - db
db:
  image: mysql
  ports:
    - 3306:3306
  environment:
    - MYSQL_USER=user
    - MYSQL_PASSWORD=pass
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_DATABASE=tickets

